version: "3"
services:
  gpt-investar-jupyter:
    # $(id -u):$(id -g)
    # user: 1000:1000
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    volumes:
      - ../:/app
      #- /media/jpien/misc_data/ml4t/data:/data
    ports:
      - "8888:8888"
